"""add document foundation

Revision ID: b51aeba4857f
Revises: df31ba4869d9
Create Date: 2026-09-06 11:15:08.874007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b51aeba4857f'
down_revision: Union[str, Sequence[str], None] = 'df31ba4869d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('document_type', sa.Enum('GOAL', 'ROLE', 'RESPONSIBILITY', 'ONE_TO_ONE', 'DEVELOPMENT', 'PERSONAL_EVIDENCE', name='document_type'), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=200), nullable=False),
    sa.Column('storage_path', sa.String(length=2000), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=500), nullable=True),
    sa.Column('effective_start', sa.Date(), nullable=True),
    sa.Column('effective_end', sa.Date(), nullable=True),
    sa.Column('content_hash', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('UPLOADED', 'PROCESSED', 'FAILED', name='document_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_content_hash'), 'documents', ['content_hash'], unique=False)
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_content_hash'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
