"""create initial MyImpact schema

Revision ID: df31ba4869d9
Revises: 
Create Date: 2026-09-05 08:59:55.903560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df31ba4869d9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('evidence',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('source_type', sa.Enum('JIRA', 'GITHUB', 'CONFLUENCE', 'WORKDAY', 'PERSONAL', 'DOCUMENT', 'OTHER', name='evidence_source_type'), nullable=False),
    sa.Column('source_id', sa.String(length=500), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=2000), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_hash', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', 'DELETED', name='evidence_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evidence_source', 'evidence', ['source_type', 'source_id'], unique=False)
    op.create_index(op.f('ix_evidence_user_id'), 'evidence', ['user_id'], unique=False)
    op.create_table('goals',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'COMPLETED', 'ARCHIVED', name='goal_status'), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goals_user_id'), 'goals', ['user_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('report_type', sa.Enum('MONTHLY_IMPACT', 'QUARTERLY_IMPACT', 'ANNUAL_PERFORMANCE', 'GOAL_PROGRESS', 'PROMOTION_EVIDENCE', 'ONE_TO_ONE', name='report_type'), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('CURRENT', 'STALE', 'ARCHIVED', name='report_status'), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_user_id'), 'reports', ['user_id'], unique=False)
    op.create_table('evidence_mappings',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('evidence_id', sa.String(length=64), nullable=False),
    sa.Column('goal_id', sa.String(length=64), nullable=False),
    sa.Column('relevance', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='evidence_relevance'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evidence_id', 'goal_id', name='uq_evidence_goal_mapping')
    )
    op.create_index(op.f('ix_evidence_mappings_evidence_id'), 'evidence_mappings', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_evidence_mappings_goal_id'), 'evidence_mappings', ['goal_id'], unique=False)
    op.create_table('evidence_versions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('evidence_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evidence_id', 'version', name='uq_evidence_version')
    )
    op.create_index(op.f('ix_evidence_versions_evidence_id'), 'evidence_versions', ['evidence_id'], unique=False)
    op.create_table('impact_assessments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('evidence_id', sa.String(length=64), nullable=False),
    sa.Column('goal_id', sa.String(length=64), nullable=False),
    sa.Column('impact_type', sa.Enum('TECHNICAL', 'BUSINESS', 'CUSTOMER', 'RELIABILITY', 'PERFORMANCE', 'AUTOMATION', 'LEADERSHIP', 'MENTORING', 'INNOVATION', 'OPERATIONAL', name='impact_type'), nullable=False),
    sa.Column('impact_summary', sa.Text(), nullable=False),
    sa.Column('impact_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('assessment_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_impact_assessments_evidence_id'), 'impact_assessments', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_impact_assessments_goal_id'), 'impact_assessments', ['goal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_impact_assessments_goal_id'), table_name='impact_assessments')
    op.drop_index(op.f('ix_impact_assessments_evidence_id'), table_name='impact_assessments')
    op.drop_table('impact_assessments')
    op.drop_index(op.f('ix_evidence_versions_evidence_id'), table_name='evidence_versions')
    op.drop_table('evidence_versions')
    op.drop_index(op.f('ix_evidence_mappings_goal_id'), table_name='evidence_mappings')
    op.drop_index(op.f('ix_evidence_mappings_evidence_id'), table_name='evidence_mappings')
    op.drop_table('evidence_mappings')
    op.drop_index(op.f('ix_reports_user_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_goals_user_id'), table_name='goals')
    op.drop_table('goals')
    op.drop_index(op.f('ix_evidence_user_id'), table_name='evidence')
    op.drop_index('ix_evidence_source', table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
